server:
  port: 8088
  servlet:
    context-path: /bootcamp

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: postgres://qydtjtbezovbvz:07adedcfe308afa32563d4947b2e7b6362b322dc82f1789349671884e9c95ca9@ec2-18-214-195-34.compute-1.amazonaws.com:5432/df37kfdbbmt7cm
    username: qydtjtbezovbvz
    password: 07adedcfe308afa32563d4947b2e7b6362b322dc82f1789349671884e9c95ca9
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    generate-ddl: true
    hibernate:
      ddl-auto: none

application:
  description: Projeto criado para o BootCamp DIO - Santander